from instagrapi import Client
from instagrapi.types import Usertag, Location, List
import time
# set instagram credentials 
ACCOUNT_USERNAME='comedy_cementary'
ACCOUNT_PASSWORD='Rishabh@2021'
cl = Client()
cl.login(ACCOUNT_USERNAME, ACCOUNT_PASSWORD)

user_id = cl.user_id_from_username(ACCOUNT_USERNAME)
print(user_id)
user = cl.user_info_by_username(ACCOUNT_USERNAME)
print(user)

#medias = cl.photo_upload(path=['/app/dank/0_stefán_karl_stefánsson_is_the_meme_of_the_year.jpg'], caption='memes #memes')
#time.sleep(3600)
#medias = cl.photo_upload(path=['/app/dank/10_will_probably_have_a_similar_interaction_with_my.jpg'], caption='memes #memes')
#time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/11_my_grades_f.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/12_i_would_not_be_surprised.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/13_posted_from_school.png'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/14_50_holy_damage.png'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/15_damn_you_bill_gates.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/16_pretty_much.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/17_it_aint_muchbut_its_honest_work.png'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/18_ya_yoink.png'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/19_we_are_ass_bröthers.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/1_didnt_disappoint.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/20_justice_for_depp.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/21_so_much_sexier.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/22_any_second_now.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/23_its_only_logical.png'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/24_all_the_kings_out_there_stay_strong.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/25_you_get_what_you_fucking_deserve.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/26_bernie_on_a_chair_inauguration.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/27_netflix_be_following_them_everywhere.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/28_or_any_of_those_shows.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/29_this_should_not_have_taken_as_long_as_it_did_to.png'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/2_college_man.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/30_joe_mama.png'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/31_pepe_the_frog_is_your_meme_of_the_decade.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/32_this_is_by_far_and_away_the_worst_meme_i_have.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/33_not_anymore.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/34_first_world_problems.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/35_looks_like_youre_in_need_of_an_ed_u_cation.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/36_capitalism_is_dead_long_live_the_power_of_memes.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/37_just_give_me_a_chance.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/38_i_dont_blame_them.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/39_embrace_tradition.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/3_enough_with_the_awards_ok.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/40_i_hope_no_one_is_watching.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/41_a_chemistry_meme.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/42_bruh_moment.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/43_soon.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/44_peach_is_a_hoe.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/45_privacy_my_ass.png'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/46_happy_halloween.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/47_well_its_true.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/48_he_just_always_has.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/49_200_iq_subreddit.png'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/4_damn_i_didnt_know_mods_played_pc.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/50_just_my_luck.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/51_quite_surprised_i_havent_seen_many_memes_about.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/52_blindass_op.png'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/53_the_pain_in_unreal_bro.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/54_remember_to_wash_your_hands.png'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/55_wow_they_are_so_old.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/56_sad_third_wheel_noises.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/57_being_bad_at_your_job_isnt_a_flex.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/58_it_all_comes_full_circle.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/59_fast.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/5_hopefully_he_doesnt_fail_me.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/60_using_pornhub_for_more_than_just_porn.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/61_u_have_been_punished_with_10_years_of_bonk.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/62_i_dont_want_to_hurt_them.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/63_yeah_dad_why.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/64_you_know_what_nazis_rule_the_world.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/65_im_sorry_little_one.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/66_almost.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/67_a_sad_story.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/68_not_the_message_america_wants_but_the_message.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/69_no_rush_yall.png'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/6_noted.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/70_happy_birthday_indeed.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/71_works_every_time.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/72_everitime.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/73_nobody_reads_the_title.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/75_what_if_mexicans_had_feelings.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/76_tom_jerry_is_your_2019_meme_of_the_year.png'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/77_it_really_do_be_like_that.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/78_okay_guys_hear_me_out_i_have_an_idea.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/79_hits_home_doesnt_it.png'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/7_i_know.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/80_trust_no_one_not_even_yourself.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/81_fuck_nestle.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/82_sigh.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/83_i_hope_people_are_also_up_at_3_am.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/84_all_of_that_stress_just_to_be_ejected_part_3_of.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/85_inhales.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/86_kung_flu_intensifies.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/87_oh_no.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/88_yall_ready.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/89_fucking_legends.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/8_sorry_i_dont_speak_ar15.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/90_it_was_time_for_thomas_to_leave_he_had_seen.png'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/91_dont_say_i_didnt_warn_you.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/92_why_must_you_hurt_me_in_this_way.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/93_here_you_go_comrades.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/94_the_colonies_know.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/95_it_really_do_be_like_that.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/96_what_more_do_you_want_from_me.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/97_based_on_a_true_story.png'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/98_yall_know_this_is_true_lmao.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/99_the_only_good_thing_in_my_life.jpg'], caption='memes #memes')
time.sleep(3600)
medias = cl.photo_upload(path=['/app/dank/9_hasbruh_moment.jpg'], caption='memes #memes')
time.sleep(3600)
